In [1]:
import numpy as np

In [23]:
X = np.array(
    [[4, 1],
    [1, 0],
    [2, 5],
    [3, 4]]
)
X

array([[4, 1],
       [1, 0],
       [2, 5],
       [3, 4]])

In [24]:
X_centered = np.array(
    [[1.5, -1.5],
    [-1.5, -2.5],
    [-.5, 2.5],
    [.5, 1.5]]
)
X_centered

array([[ 1.5, -1.5],
       [-1.5, -2.5],
       [-0.5,  2.5],
       [ 0.5,  1.5]])

In [25]:
X_centered.T @ X_centered

array([[ 5.,  1.],
       [ 1., 17.]])

In [26]:
1/4 * X_centered.T @ X_centered

array([[1.25, 0.25],
       [0.25, 4.25]])

In [27]:
cov = np.array(1/4 * X_centered.T @ X_centered)
cov

array([[1.25, 0.25],
       [0.25, 4.25]])

In [28]:
from numpy import linalg as LA
eigenvalues, eigenvectors = LA.eig(cov)

In [29]:
eigenvalues

array([1.22930937, 4.27069063])

In [30]:
eigenvectors

array([[-0.99659268, -0.08248053],
       [ 0.08248053, -0.99659268]])

In [31]:
PC1 = eigenvectors[np.argmax(eigenvalues)]
PC1

array([ 0.08248053, -0.99659268])

In [32]:
X.shape

(4, 2)

In [33]:
eigenvectors[1].shape

(2,)

In [34]:
Y1 = X @ eigenvectors[1]
Y2 = X @ eigenvectors[0]

In [35]:
Y1

array([-0.66667055,  0.08248053, -4.81800232, -3.73892911])

In [36]:
Y2

array([-4.06885124, -0.99659268, -2.40558801, -3.31970015])

part b

In [37]:
PC1 = eigenvectors[1]
proposed_vector = np.array(
    [PC1[1], -PC1[0]]
)

In [38]:
proposed_vector

array([-0.99659268, -0.08248053])